### ISSUE TITLE
JoomlaTools Assignment Issue in Joomla 3.9

### ISSUE THREAD

**Issue by simmonsr** [joomlatools/joomlatools-framework#231] opened 2018-11-28 19:46 UTC
With JoomlaTools Framework plugin enabled, Templates that have specific Assignments (and are not the default) do not show changes from that template (ie modifying template / background color). This is especially troubling for templates that use the Gantry 5 framework as Assignments are used frequently.

#### Steps to reproduce the behavior

1. Create a Duplicate of ProtoStar template.
2. Assign this Duplicate of ProtoStar to your Home menu.
3. Change the Template / Background Color of Duplicate of ProtoStar.
4. View the Frontend and you will see that color has not changed.
5. Disable Joomlatools plugin and then view the frontend and then you will see the color has changed.

**Comment by johanjanssens** [comment] 2018-11-29 03:56
​Thanks for the further information. We have look deeper into this. 

1. We cannot replicate the issue with ONLY our framework and extensions installed.

2. We can only replicate the problem with Ohanah 3.2 installed.

Upon further investigation we have found that new Ohanah 3.=é release, which has been upgraded for compatibility with our Joomlatools Framework introduces a packaging bug.  Parts of the package still contain plugins for the older version of the framework and are likely the cause of this issue. I have Ohanah support abou this.

I'm closing this issue report.

**Closed by johanjanssens** 2018-11-29 03:56 UTC

**Comment by mediaateam** [comment] 2018-12-05 01:53
Ok, leaving an update on this, it was that the JoomlaTool's extensions needed updates, but they don't show that they need updates in Joomla. Updating them fixed the issue with Gantry 5 for us.

**Comment by johanjanssens** [comment] 2018-12-05 09:17
For product support for our extensions please use our support system at hhttp://support.joomlatools.com we are most happy to assist you from there.
