### ISSUE TITLE
Form overrides not picked correctly

### ISSUE THREAD

**Issue by johanjanssens** [joomlatools/joomlatools-framework#145] opened 2018-03-16 23:21 UTC
See: https://support.joomlatools.com/tickets/topic/8720
See: https://support.joomlatools.com/tickets/topic/8713-hide-permissions-and-featured-image-on-uploading-files-or-creating-new-categories

**Comment by ercanozkaya** [comment] 2018-03-19 17:47
Duplicate of #117

**Closed by ercanozkaya** 2018-03-19 17:47 UTC
Labels: bug
